favouriteMedia: hide gif tag on images/videos
moonlight-mod/extensions pull request #12
Opened 2023-12-09 22:15 UTC by ImLvna

2023-12-09 23:36 UTC, NotNite requested changes
Your extension hardcodes CSS classes which will change on Discord updates. Please use syntax like `[class*="originalLink_"]`.

2023-12-09 23:52 UTC, ImLvna commented
fixed!

2023-12-09 23:53 UTC, ImLvna commented
waa wheres the button to mark requests as resolved

2023-12-10 00:15 UTC, NotNite approved these changes

2023-12-10 00:15 UTC, merged